# NYU semseg config
seed : 800

# Finetune from:
finetune:  "/root/datasets/multimae-b_98_rgb+-depth-semseg_1600e_multivit-afff3f8c (1).pth"

# Input tasks
in_domains: rgb

# Architecture
model: multivit_base
patch_size: 16
num_global_tokens: 1
drop_path_encoder: 0.1
output_adapter: convnext
decoder_dim: 6144
decoder_preds_per_patch: 16
decoder_depth: 4

# Train
epochs: 1000
opt: adamw
lr: 0.0005 # = 1e-4
warmup_lr: 0.00005 # = 1e-6
min_lr: 0.000001
warmup_epochs: 1
train_batch_size: 16
test_batch_size : 64
input_size: 336
layer_decay: 0.9

# Augmentation
aug_name: simple

# Data info
data_path: "/root/datasets/NYUv2_Dataset/NYUv2/NYUv2/train"
eval_data_path: "/root/datasets/NYUv2_Dataset/NYUv2/NYUv2/test" # Change me
num_classes: 40
dataset_name: nyu
dist_eval: True
seg_reduce_zero_label: True
eval_freq: 10

# Misc.
find_unused_params: False

#prompt
prompt_mode : deep
prompt_pool : True
prompt_shallow : False
prompt_deep : True
use_prompt_mask : True
top_k : 5
size : 10
length : 20
task_specific_prompt_length : 1
not_self_attn : False

# Wandb and l0ogging
log_wandb: False # Set to True to log to Weights & Biases
wandb_project:  'multimae-multi-l2p-deep-Testing-masking'
wandb_entity: null # Change if needed
wandb_run_name: 'test_for_masking_prompt(from_pool)_with_output_adapter_self_attention-rpo(cross_prompt_mask)(0,1,2/8,9,10,11)'
log_images_wandb: False
log_images_freq: 20
output_dir: '/root/workspace/Results/Test-masking'